version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mal-api-dev
    volumes:
      - .:/app
      - rider-cache:/root/.idea
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: 1
    ports:
      - "8000:8000"
      - "8001:8001"
    command: ["dotnet", "watch", "run"]

volumes:
  rider-cache: