name: Bugfix Pull Request Auto-Approve

on:
  pull_request_target:
    branches:
      - development

jobs:
  auto-approve-bugfix:
    if: startsWith(github.head_ref, 'bugfix/')
    runs-on: ubuntu-latest

    steps:
      - name: Auto-approve bugfix pull request
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
