name: Auto-Approve Pull Requests from bugfix branches.

on:
  pull_request_target:
    branches:
      - development

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve-bugfix:
    if: startsWith(github.head_ref, 'bugfix/')
    runs-on: ubuntu-latest

    steps:
      - name: Auto-approve bugfix pull request
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge bugfix pull request
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
