name: Auto-Approve Pull Requests from bugfix branches.

on:
  pull_request_target:
    branches:
      - development

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve-bugfix:
    if: startsWith(github.head_ref, 'bugfix/')
    runs-on: ubuntu-latest
    env:
      TOKEN1: ${{ secrets.BOT_ADMIN_TOKEN1 }}
      TOKEN2: ${{ secrets.ADMIN_TOKEN2 }}
      
    steps:
      - name: Try auto-approving with fallback tokens
        run: |
          approve() {
            echo "Trying with token (redacted)"
            curl -s -X POST \
              -H "Authorization: token $1" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
              -d '{"event":"APPROVE"}'
          }

          # Try with TOKEN1, fallback to TOKEN2
          approve "$TOKEN1" || approve "$TOKEN2"
