name: CI/CD Pipeline (LinearRegressionModelTrainingService)

on:
  push:
    branches:
      - main
    paths:
      - 'python/model_training_service_linear_regression/**'
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies (editable + dev)
        working-directory: python/model_training_service_linear_regression
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests (unit & integration)
        working-directory: python/model_training_service_linear_regression
        run: |
          pytest tests/unit tests/integration --maxfail=1 --disable-warnings -q

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: python/model_training_service_linear_regression
          file: python/model_training_service_linear_regression/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/linear-regression-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/linear-regression-service:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MALTRAINING_LIN_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MALTRAINING_LIN_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MALTRAINING_LIN_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Container App
        run: |
         az containerapp update \
          --name mal-training-linear-regression \
          --resource-group SEP4_MAL_team \
          --image ${{ secrets.DOCKERHUB_USERNAME }}/linear-regression-service:${{ github.sha }}
