name: CI/CD Pipeline (RandomForestModelTrainingService)

on:
  push:
    branches:
      - main
    paths:
      - 'python/model_training_service_randomforest/**'
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies (editable + dev)
        working-directory: python/model_training_service_randomforest
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests (unit & integration)
        working-directory: python/model_training_service_randomforest
        run: |
          PYTHONPATH=src_rf pytest tests/unit tests/integration --maxfail=1 --disable-warnings -q

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: python/model_training_service_randomforest
          file: python/model_training_service_randomforest/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/randomforest-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/randomforest-service:latest
