name: CI/CD Pipeline (API)

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check directory structure
        run: ls -la && ls -la API && ls -la API.Tests

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore API/API.csproj
          dotnet restore API.Tests/API.Tests.csproj

      - name: Build solution
        run: dotnet build API/API.csproj --configuration Release

      - name: Run tests
        run: dotnet test API.Tests/API.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: API/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api:latest

      - name: Validate API Docker image
        run: |
          docker run --rm -d -p 8081:8080 ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
          sleep 5
          curl -f http://localhost:8081/sensor/data || exit 1
          docker stop $(docker ps -q --filter "ancestor=${{ secrets.DOCKERHUB_USERNAME }}/api:latest")
        env:
          DOCKER_BUILDKIT: 1
