name: CI/CD Pipeline (API)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check directory structure
        run: ls -la && ls -la dotnet/MAL-API/API

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore dotnet/MAL-Microservice.sln

      - name: Build solution
        run: dotnet build dotnet/MAL-API/API/API.csproj --configuration Release

      - name: Run tests
        run: dotnet test dotnet/MAL-Microservice.sln --configuration Release --verbosity normal

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: dotnet
          file: dotnet/MAL-API/API/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api:latest

      - name: Validate API Docker image
        run: |
          docker run --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
          sleep 5
          curl -f http://localhost:8080/sensor/data || exit 1
          docker stop $(docker ps -q --filter "ancestor=${{ secrets.DOCKERHUB_USERNAME }}/api:latest")
        env:
          DOCKER_BUILDKIT: 1

      # 🔽 Azure deployment step added here
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MALAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MALAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MALAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name mal-api \
            --resource-group SEP4_MAL_team \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/mal-api:latest
