# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ci-cd - AzureFunction - SEP4PredictionApp

on:
  push:
    branches:
      - main
    paths:
      - 'dotnet/MAL-Prediction-Build-Service/AzureFunctions/AzureFunction.SoilHumidityPrediction/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'dotnet/MAL-Prediction-Build-Service/AzureFunctions/AzureFunction.SoilHumidityPrediction'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/AzureFunction.SoilHumidityPrediction.csproj

      - name: Build Azure Function project
        run: dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/AzureFunction.SoilHumidityPrediction.csproj --configuration Release --output ./output
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C787B792079B40659733DEBE78212738 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21FD5CE33F2B4B62A79E44720F82C3DC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BD12108B0464774A124DF13BD380AAF }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'SEP4PredictionApp'
          slot-name: 'Production'
          package: './output'
          
