name: CI/CD Pipeline (Mal Prediction Service)

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check directory structure
        run: ls -la && ls -la dotnet/prototype/MAL-Api-Service/

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore MAL-Microservice.sln

      - name: Run tests
        run: dotnet test MAL-Microservice.sln --configuration Release --verbosity normal

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dotnet/prototype/MAL-Api-Service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mal-service-api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mal-service-api:latest

      - name: Validate Docker image
        run: |
          docker run --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/mal-service-api:latest
          sleep 5  # Give the container time to start
          curl -f http://localhost:8080/Prototype/testEndpoint || exit 1
          docker stop $(docker ps -q --filter "ancestor=${{ secrets.DOCKERHUB_USERNAME }}/mal-service-api:latest")
        env:
          DOCKER_BUILDKIT: 1
