name: Auto-Approve Bugfix Pull Requests

on:
  pull_request:
    branches:
      - development
    types: [opened, reopened]

jobs:
  auto-approve-bugfix:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name
        id: check_branch
        run: |
          if [[ "${{ github.head_ref }}" == bugfix/* ]]; then
            echo "IS_BUGFIX=true" >> $GITHUB_ENV
          else
            echo "IS_BUGFIX=false" >> $GITHUB_ENV

      - name: Auto-approve bugfix PRs
        if: env.IS_BUGFIX == 'true'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
